Month 9/step 1
AlexeyKondratjev/react-burger pull request #4
Opened 2022-12-26 18:12 UTC by AlexeyKondratjev

Сделано в первом приближении перед ревью.

2022-12-26 19:47 UTC, andryxxa93 requested changes
Всё отлично работает. Роуты настроены корректно. Понравилось, что вы объединили в 
ProtectedRoute логику для авторизованных и не авторизованных пользователей. Ещё понравилась ваша страница 404.

Есть пару проблем, которые следует исправить чтобы работа была принята.

1. После успешного восстановления пароля необходимо редиректить пользователя на страницу логина.
2. Если зайти на `/profile/orders` то ссылка "Личный кабинет" в хедере перестаёт быть активной, хотя должна таковой оставаться ведь это её вложенный маршрут.
3. При запросах, использующих accessToken, должен проверяется ответ сервера. Если время жизни токена истекло (403 ошибка - оце expired), то должен выполняться запрос обновления токена и повторяться запрос, который не был выполнен успешно. 
<img width="1440" alt="Снимок экрана 2022-12-26 в 22 45 53" src="https://user-images.githubusercontent.com/60173362/209579382-313bbb0c-8ffa-4915-a7ea-80c5ce672c7c.png">

Рекомендую добавить в `gitignore` папку `.vscode` - так как не все используют этот IDE и на github он не нужен.

Удачных правок!

2022-12-28 05:46 UTC, andryxxa93 requested changes
Всё отлично. Только по-прежнему не происходит обновление токена если тот протух. Проверить это можно залогинившись подождать 20 минут попробовать обновить данные пользователя.

Можете использовать для этого обертку над fetch, примерно такую
```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};

const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options); //делаем запрос
    return await checkReponse(res);
  } catch (err) {
    if (err.message === "jwt expired") {
      const refreshData = await refreshToken(); //обновляем токен
      localStorage.setItem("refreshToken", refreshData.refreshToken);
      localStorage.setItem("accessToken", refreshData.accessToken); //(или в cookies)
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options); //вызываем перезапрос данных
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};

2022-12-28 13:27 UTC, andryxxa93 requested changes
Теперь токен обновляется, но есть проблема, он конкатенируется с существующим токеном - из-за этого опять возникает ошибка.
![Снимок экрана 2022-12-28 в 16 26 00](https://user-images.githubusercontent.com/60173362/209819482-cf90198c-d850-443d-a535-c5f5d9c3bf6b.png)

2022-12-28 16:43 UTC, AlexeyKondratjev commented
Замечание справедливое. Но было бы неплохо, если бы вы в будущем точнее указывали при каких обстоятельствах возникает ошибка. Думая, что это относится все к тому же обновлению токена и повторному запросу данных пользователя через 20 мин бездействия, я потратил немало времени. Пока не заметил, что у вас на скриншоте PATCH-запрос...

2022-12-29 11:46 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

2022-12-29 12:21 UTC, merged